### ISSUE TITLE
treeherder-client package in requirements.txt is unused

### ISSUE THREAD

**Issue by edmorley** [mozilla-services/fxa-testing-e2e#23]
I don't think the package is used anywhere?
https://github.com/mozilla-services/fxa-testing-e2e/blob/3216f3ded6e953eebd067b25bc03bfcb8d375fe6/requirements.txt#L13

**Comment by shane-tomlinson** [comment]
@vladikoff - any idea?

**Comment by edmorley** [comment]
Ah whilst the client isn't used directly (there are no references to the only module it provides, `thclient`), it's used by mozdownload, which presumably ended up in requirements.txt due to a `pip freeze > requirements.txt`. (Not a bad thing, since pinning all dependencies is a good thing).

I'll file new issues to (a) update it, (b) start using pyup.io to do this automatically.
