### ISSUE TITLE
Use pyup.io to keep Python dependencies up to date

### ISSUE THREAD

**Issue by edmorley** [mozilla-services/fxa-testing-e2e#24]
Several Mozilla projects now use https://pyup.io/ to automatically open PRs when their Python packages have new releases available. Perhaps it's a good fit for this project too?

Search for "pyup" in this guide for more info:
https://wiki.mozilla.org/Security/FirefoxOperations#Security_Checklist

(Context: keeping the treeherder-client package up to date to help the Treeherder team deprecate API features more expediently)

Many thanks!

**Comment by vladikoff** [comment]
Fixed up in https://github.com/mozilla-services/fxa-testing-e2e/pull/32 plus added pyup, thanks!
