### ISSUE TITLE
Migrate to CircleCI 2

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/fxa-testing-e2e#33]
I recently got an email from "The CircleCI Team" saying:

> Last month, we pointed you toward resources to help you migrate active projects from CircleCI 1.0 to 2.0 with the [Migration Center](http://go.circleci.com/Q0MH0GM0Zn2GW0k120044I0). 
>
> [With only 30 days left until CircleCI 1.0 sunsets](https://circleci.com/sunset1-0/), we want to ensure you have everything you need to help you with any active projects that still need to migrate to 2.0. Our team has been busy creating resources and new features to help make it easier:

More info in the CircleCI Blog at https://circleci.com/blog/sunsetting-1-0/ and https://circleci.com/docs/2.0/migration-intro/

I also found https://circleci.com/docs/2.0/local-cli/ which points to a handy CircleCI v2 config validator (using something like <kbd>$ circleci config validate -c .circleci/config.yml</kbd>).

**Comment by vladikoff** [comment]
@pdehaan Any other repos ?

**Comment by pdehaan** [comment]
I think this one and **mozilla/fxa-content-server** (which was _just_ fixed via https://github.com/mozilla/fxa-content-server/pull/6410) were the only two "FxA-ish" repos I found that weren't archived that were using a .circle.yml file that didn't specify a `version` number (or was less than "2").

Although that wouldn't account for all the dependencies that you have forked and are running from your personal GitHub accounts.

But if you have doubts, I can write up a quick scanner that checks all the repos mentioned in https://github.com/mozilla/fxa/blob/master/scripts/repos.txt

Or, you could try using https://github.com/CircleCI-Public/find-circle-yml and running it against the mozilla org (and cross your fingers that you don't have a metric ton of noise).

**Comment by pdehaan** [comment]
OK, here's a hacky script which scans all the fxa-* repos:

```js
const {readFileSync} = require("fs");

const octokit = require("@octokit/rest")();
const yaml = require("js-yaml");

const FXA_REPOS = readFileSync(require.resolve("fxa/scripts/repos.txt"), "utf-8")
  .trim()
  .split("\n")
  .filter(line => !line.startsWith("#"))
  .map(repo => repo.indexOf("/") !== -1 ? repo : `mozilla/${repo}`)
  .sort();

octokit.authenticate({
  type: "oauth",
  token: "{{ GITHUB_TOKEN_HERE }}"
});

async function scan() {
  for (const r of FXA_REPOS) {
    try {
      const [owner, repo] = r.split("/");
      const res = await octokit.repos.getContent({owner, repo, path: "circle.yml"});
      console.log(`FOUND! https://github.com/${owner}/${repo}/blob/master/circle.yml`);
    } catch (err) {
      console.error(`ERROR! ${r}: ${JSON.parse(err.message).message}`);
    }
  }
}

scan();
```

### Output:

```
FOUND! https://github.com/mozilla-services/fxa-testing-e2e/blob/master/circle.yml
ERROR! mozilla/123done: Not Found
ERROR! mozilla/PyFxA: Not Found
ERROR! mozilla/browserid-local-verify: Not Found
ERROR! mozilla/browserid-verifier: Not Found
ERROR! mozilla/fxa: Not Found
ERROR! mozilla/fxa-activity-metrics: Not Found
ERROR! mozilla/fxa-amplitude-send: Not Found
ERROR! mozilla/fxa-auth-db-mysql: Not Found
ERROR! mozilla/fxa-auth-server: Not Found
ERROR! mozilla/fxa-basket-proxy: Not Found
ERROR! mozilla/fxa-bugzilla-mirror: Not Found
ERROR! mozilla/fxa-checkbox: Not Found
ERROR! mozilla/fxa-common-password-list: Not Found
ERROR! mozilla/fxa-content-server: Not Found
ERROR! mozilla/fxa-content-server-l10n: Not Found
ERROR! mozilla/fxa-crypto-relier: Not Found
ERROR! mozilla/fxa-customs-server: Not Found
ERROR! mozilla/fxa-dev: Not Found
ERROR! mozilla/fxa-easter-egg: Not Found
ERROR! mozilla/fxa-email-service: Not Found
ERROR! mozilla/fxa-geodb: Not Found
ERROR! mozilla/fxa-js-client: Not Found
ERROR! mozilla/fxa-js-client-old: Not Found
ERROR! mozilla/fxa-jwtool: Not Found
ERROR! mozilla/fxa-local-dev: Not Found
ERROR! mozilla/fxa-oauth-client: Not Found
ERROR! mozilla/fxa-oauth-console: Not Found
ERROR! mozilla/fxa-oauth-server: Not Found
ERROR! mozilla/fxa-profile-server: Not Found
ERROR! mozilla/fxa-python-client: Not Found
ERROR! mozilla/fxa-relier-client: Not Found
ERROR! mozilla/fxa-retention-metrics: Not Found
ERROR! mozilla/fxa-shared: Not Found
ERROR! mozilla/fxa-sprint-planning: This repository is empty.
ERROR! mozilla/grunt-l10n-lint: Not Found
ERROR! mozilla/hapi-fxa-oauth: Not Found
ERROR! mozilla/mozlog: Not Found
```

If you want to read the contents of the base64'ed file, we'd need to parse the YAML config file and grab the `version` property. But since there was only one repo that had a "config.yml" file, it didn't seem to be worth the hassle.

```js
function base64Yaml({content="", encoding="base64"}) {
  const decoded = new Buffer(content, encoding).toString("ascii");
  return yaml.safeLoad(decoded);
}
```

**Comment by vladikoff** [comment]
niceeee!
